from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List

from prompt_utils import strip_eos
try:
    from event_relation_prompt import parse_candidate_label
except Exception:
    parse_candidate_label = None


def read_jsonl(path: str | Path) -> Iterable[Dict[str, Any]]:
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def lcs_len(a: List[str], b: List[str]) -> int:
    dp = [0] * (len(b) + 1)
    for x in a:
        prev = 0
        for j, y in enumerate(b, start=1):
            tmp = dp[j]
            if x == y:
                dp[j] = prev + 1
            else:
                dp[j] = max(dp[j], dp[j - 1])
            prev = tmp
    return dp[-1]


def rouge_l_char(pred: str, ref: str) -> float:
    pred_chars = list(pred.strip())
    ref_chars = list(ref.strip())
    if not pred_chars or not ref_chars:
        return 0.0
    lcs = lcs_len(pred_chars, ref_chars)
    prec = lcs / len(pred_chars)
    rec = lcs / len(ref_chars)
    if prec + rec == 0:
        return 0.0
    return 2 * prec * rec / (prec + rec)


def normalize_answer(text: str) -> str:
    return "".join(strip_eos(text).split())


def main() -> None:
    parser = argparse.ArgumentParser(description="Simple exact-match and char-level ROUGE-L evaluation.")
    parser.add_argument("--pred_file", required=True, help="JSONL generated by infer.py; must contain prediction and completion/output/answer.")
    args = parser.parse_args()

    rows = list(read_jsonl(args.pred_file))
    if not rows:
        raise ValueError("Empty prediction file.")

    exact = 0
    parsed_exact = 0
    rouge_scores = []
    has_candidates = False
    for row in rows:
        pred = row.get("prediction", "")
        ref = row.get("gold_label") or row.get("completion") or row.get("output") or row.get("answer") or row.get("target") or ""
        ref_clean = strip_eos(str(ref))
        pred_norm = normalize_answer(pred)
        ref_norm = normalize_answer(ref_clean)
        exact += int(pred_norm == ref_norm)
        rouge_scores.append(rouge_l_char(pred, ref_clean))
        if parse_candidate_label is not None and row.get("candidates"):
            has_candidates = True
            parsed = row.get("parsed_prediction") or parse_candidate_label(pred, row["candidates"])
            parsed_exact += int(parsed == ref_clean)

    metrics = {
        "n": len(rows),
        "exact_match": exact / len(rows),
        "rouge_l_char": sum(rouge_scores) / len(rouge_scores),
    }
    if has_candidates:
        metrics["candidate_accuracy"] = parsed_exact / len(rows)
    print(json.dumps(metrics, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
